# Pulling Data from endpoint section

## Initial endpoint exploration

Initial setup, exploring the first page and the JSON keys and how it is structured

In [44]:
import requests
import json
import pandas as pd

In [45]:
## Initial exploration of data from importing endpoint and see which status code is returned
endpoint = 'https://europe-west3-recap-dev-347108.cloudfunctions.net/analytics-challenge-api/invoices?page=1'
response = requests.get(endpoint)
print(response.status_code)

200

In [46]:
## Retrieve sample json data from endpoint
data_import = response.json()

## Check the keys in json data
data_import.keys()

dict_keys(['data', 'page', 'page_size', 'total_items', 'total_pages'])

In [47]:
## Check data per key

for i in data_import.keys():
    print(data_import[i])

[{'company_id': 'ed811a71-439e-4c49-bfb8-8fb407c39428', 'company_name': 'DataLake Ventures', 'counter_party': 'Wholesale Dynamics GmbH', 'created_at': '2025-01-01 12:00:00', 'currency': 'EUR', 'invoice_date': '2025-01-01', 'invoice_due_date': '2025-02-15', 'invoice_id': '895a6833-d83d-4a5a-a2c3-de35b341d00a', 'invoice_number': 'INV-2025-0023', 'totalAmount': 648.15}, {'company_id': '2219af27-6da7-41a3-ac79-abce340fe56d', 'company_name': 'CloudStream Insights', 'counter_party': 'Global Services Ltd', 'created_at': '2025-01-01 08:00:00', 'currency': 'EUR', 'invoice_date': '2025-01-01', 'invoice_due_date': '2025-02-15', 'invoice_id': '4140125e-1f9b-41fb-8af2-df7996ea1e48', 'invoice_number': 'INV-2025-0239', 'totalAmount': 2141.18}, {'company_id': 'da36911c-7145-4c19-8e82-35c39f3a2e9c', 'company_name': 'AlgoRhythm Solutions', 'counter_party': 'Cloud Systems', 'created_at': '2025-01-01 10:00:00', 'currency': 'EUR', 'invoice_date': '2025-01-01', 'invoice_due_date': '2025-03-02', 'invoice_id': 'abed77a5-4581-42f9-adb1-9ca99837e78f', 'invoice_number': 'INV-2025-0427', 'totalAmount': 3474.1}, {'company_id': 'cc007a93-8d8e-444c-bb8c-ae3db9871347', 'company_name': 'ByteForge Analytics', 'counter_party': 'Enterprise Solutions AG', 'created_at': '2025-01-01 02:00:00', 'currency': 'GBP', 'invoice_date': '2025-01-01', 'invoice_due_date': '2025-03-02', 'invoice_id': 'e0e417e9-c2f2-459c-a296-2bc9ca406638', 'invoice_number': 'INV-2025-0498', 'totalAmount': 3877.07}, {'company_id': 'd66bfb15-e693-4219-9cb0-c5ecbb61a994', 'company_name': 'ETL Enterprises', 'counter_party': 'Nordic Supply Chain', 'created_at': '2025-01-01 05:00:00', 'currency': 'EUR', 'invoice_date': '2025-01-01', 'invoice_due_date': '2025-01-31', 'invoice_id': '095795ca-2eca-499b-805d-82d79bca6cdc', 'invoice_number': 'INV-2025-0691', 'totalAmount': 1452.09}, {'company_id': 'da36911c-7145-4c19-8e82-35c39f3a2e9c', 'company_name': 'AlgoRhythm Solutions', 'counter_party': 'Wholesale Dynamics GmbH', 'created_at': '2025-01-01 12:00:00', 'currency': 'USD', 'invoice_date': '2025-01-01', 'invoice_due_date': '2025-03-02', 'invoice_id': 'a57d29ee-2055-4957-b20a-7123717c12af', 'invoice_number': 'INV-2025-0761', 'totalAmount': 4426.37}, {'company_id': 'd66bfb15-e693-4219-9cb0-c5ecbb61a994', 'company_name': 'ETL Enterprises', 'counter_party': 'European E-Commerce AG', 'created_at': '2025-01-01 00:00:00', 'currency': 'EUR', 'invoice_date': '2025-01-01', 'invoice_due_date': '2025-01-15', 'invoice_id': '83f92bfd-dc1d-46c3-b32a-5202e226a9c3', 'invoice_number': 'INV-2025-0975', 'totalAmount': 3484.68}, {'company_id': '11978bfd-02c2-42b7-989e-7b1306238c5c', 'company_name': 'Quantum Query Labs', 'counter_party': 'Global Trading Partners', 'created_at': '2025-01-02 01:00:00', 'currency': 'GBP', 'invoice_date': '2025-01-02', 'invoice_due_date': '2025-03-03', 'invoice_id': '1edcdbdd-fbca-441b-960e-7e38a804a08c', 'invoice_number': 'INV-2025-0931', 'totalAmount': 4108.09}, {'company_id': 'cc007a93-8d8e-444c-bb8c-ae3db9871347', 'company_name': 'ByteForge Analytics', 'counter_party': 'Metro Commerce Ltd', 'created_at': '2025-01-03 04:00:00', 'currency': 'EUR', 'invoice_date': '2025-01-03', 'invoice_due_date': '2025-02-17', 'invoice_id': '2aea3d0c-7142-41be-a6f9-c7f3810a6c79', 'invoice_number': 'INV-2025-0647', 'totalAmount': 1185.48}, {'company_id': '08804b48-7b03-4a08-8eff-72e3a2d1527c', 'company_name': 'Tensor Trading Ltd', 'counter_party': 'Nordic Supply Chain', 'created_at': '2025-01-04 01:00:00', 'currency': 'GBP', 'invoice_date': '2025-01-04', 'invoice_due_date': '2025-02-03', 'invoice_id': '4b032be2-f3ae-498f-abf9-84ec76fdb218', 'invoice_number': 'INV-2025-0191', 'totalAmount': 2874.97}, {'company_id': 'ed811a71-439e-4c49-bfb8-8fb407c39428', 'company_name': 'DataLake Ventures', 'counter_party': 'Wholesale Dynamics GmbH', 'created_at': '2025-01-05 12:00:00', 'currency': 'EUR', 'invoice_date': '2025-01-05', 'invoice_due_date': '2025-01-19', 'invoice_id': '8ec0cf06-3bf4-4922-8aa0-22b5a2d75e0f', 'invoice_number': 'INV-2025-0281', 'totalAmount': 4424.03}, {'company_id': 'd66bfb15-e693-4219-9cb0-c5ecbb61a994', 'company_name': 'ETL Enterprises', 'counter_party': 'BigRetail Inc', 'created_at': '2025-01-05 03:00:00', 'currency': 'GBP', 'invoice_date': '2025-01-05', 'invoice_due_date': '2025-03-06', 'invoice_id': 'd3cce89f-a733-411f-9b51-e98df176d232', 'invoice_number': 'INV-2025-0539', 'totalAmount': 3272.12}, {'company_id': 'd66bfb15-e693-4219-9cb0-c5ecbb61a994', 'company_name': 'ETL Enterprises', 'counter_party': 'Future Tech', 'created_at': '2025-01-05 00:00:00', 'currency': 'EUR', 'invoice_date': '2025-01-05', 'invoice_due_date': '2025-01-19', 'invoice_id': 'fed0dc73-269f-4e24-b6a6-1b4963e14f8a', 'invoice_number': 'INV-2025-0624', 'totalAmount': 2283.77}, {'company_id': '640cf7f1-51c7-4c74-bff4-074303a1b191', 'company_name': 'Vector Velocity Inc', 'counter_party': 'Digital Ventures', 'created_at': '2025-01-05 05:00:00', 'currency': 'EUR', 'invoice_date': '2025-01-05', 'invoice_due_date': '2025-01-19', 'invoice_id': '2a164a32-b965-47f8-aca5-9053a42b99ce', 'invoice_number': 'INV-2025-0709', 'totalAmount': 1959.2}, {'company_id': 'da36911c-7145-4c19-8e82-35c39f3a2e9c', 'company_name': 'AlgoRhythm Solutions', 'counter_party': 'Wholesale Dynamics GmbH', 'created_at': '2025-01-05 01:00:00', 'currency': 'EUR', 'invoice_date': '2025-01-05', 'invoice_due_date': '2025-01-19', 'invoice_id': 'e38ad2fb-703d-49d9-8950-f75b3307c683', 'invoice_number': 'INV-2025-0802', 'totalAmount': 1429.42}, {'company_id': 'ed811a71-439e-4c49-bfb8-8fb407c39428', 'company_name': 'DataLake Ventures', 'counter_party': 'Innovation Partners', 'created_at': '2025-01-06 12:00:00', 'currency': 'USD', 'invoice_date': '2025-01-06', 'invoice_due_date': '2025-02-05', 'invoice_id': '841a3936-5f6a-4d45-b6f7-a444a37199af', 'invoice_number': 'INV-2025-0654', 'totalAmount': 4052.05}, {'company_id': 'ed811a71-439e-4c49-bfb8-8fb407c39428', 'company_name': 'DataLake Ventures', 'counter_party': 'Digital Ventures', 'created_at': '2025-01-06 08:00:00', 'currency': 'USD', 'invoice_date': '2025-01-06', 'invoice_due_date': '2025-01-20', 'invoice_id': '966bd179-e411-4298-bd80-0c5d160ac84f', 'invoice_number': 'INV-2025-0917', 'totalAmount': 158.61}, {'company_id': '2219af27-6da7-41a3-ac79-abce340fe56d', 'company_name': 'CloudStream Insights', 'counter_party': 'Enterprise Solutions AG', 'created_at': '2025-01-07 03:00:00', 'currency': 'EUR', 'invoice_date': '2025-01-07', 'invoice_due_date': '2025-01-21', 'invoice_id': '67b70d0c-3e51-42bb-96d5-a667c37d33d9', 'invoice_number': 'INV-2025-0609', 'totalAmount': 812.1}, {'company_id': '86ebdf1a-a247-4893-866c-f6eb3e86ecee', 'company_name': 'DataWizards GmbH', 'counter_party': 'FastTrack Logistics', 'created_at': '2025-01-07 03:00:00', 'currency': 'EUR', 'invoice_date': '2025-01-07', 'invoice_due_date': '2025-02-21', 'invoice_id': '329d0f6f-772e-47c4-9d8e-df76c568a992', 'invoice_number': 'INV-2025-0614', 'totalAmount': 4357.36}, {'company_id': 'cc007a93-8d8e-444c-bb8c-ae3db9871347', 'company_name': 'ByteForge Analytics', 'counter_party': 'Smart Industries', 'created_at': '2025-01-08 02:00:00', 'currency': 'USD', 'invoice_date': '2025-01-08', 'invoice_due_date': '2025-02-22', 'invoice_id': '2a3e394f-895b-409b-94c2-874dd13389d3', 'invoice_number': 'INV-2025-0311', 'totalAmount': 2882.13}, {'company_id': '14d14894-f81d-4dc6-afbe-8e41399d4c98', 'company_name': 'Neural Networks & Co', 'counter_party': 'Nordic Supply Chain', 'created_at': '2025-01-08 08:00:00', 'currency': 'EUR', 'invoice_date': '2025-01-08', 'invoice_due_date': '2025-02-22', 'invoice_id': '9200dbad-5d06-41a8-884d-085b101209dd', 'invoice_number': 'INV-2025-0443', 'totalAmount': 4620.64}, {'company_id': 'cc007a93-8d8e-444c-bb8c-ae3db9871347', 'company_name': 'ByteForge Analytics', 'counter_party': 'Global Trading Partners', 'created_at': '2025-01-08 05:00:00', 'currency': 'EUR', 'invoice_date': '2025-01-08', 'invoice_due_date': '2025-03-09', 'invoice_id': 'fb3d49c3-80d5-4e99-beaa-7478f1873505', 'invoice_number': 'INV-2025-0744', 'totalAmount': 2159.19}, {'company_id': 'c5ccae70-d802-4502-8b25-9be976292ccb', 'company_name': 'Pipeline Pioneers AG', 'counter_party': 'TechMart Distribution', 'created_at': '2025-01-08 06:00:00', 'currency': 'USD', 'invoice_date': '2025-01-08', 'invoice_due_date': '2025-03-09', 'invoice_id': '97ba0b6b-3a2c-41c8-8e87-e7c434d7d24d', 'invoice_number': 'INV-2025-0968', 'totalAmount': 1308.61}, {'company_id': 'c5ccae70-d802-4502-8b25-9be976292ccb', 'company_name': 'Pipeline Pioneers AG', 'counter_party': 'Digital Ventures', 'created_at': '2025-01-09 12:00:00', 'currency': 'USD', 'invoice_date': '2025-01-09', 'invoice_due_date': '2025-02-23', 'invoice_id': 'a1faf548-00db-4e99-b773-25d012a799df', 'invoice_number': 'INV-2025-0241', 'totalAmount': 1789.53}, {'company_id': 'cc007a93-8d8e-444c-bb8c-ae3db9871347', 'company_name': 'ByteForge Analytics', 'counter_party': 'Metro Commerce Ltd', 'created_at': '2025-01-09 04:00:00', 'currency': 'EUR', 'invoice_date': '2025-01-09', 'invoice_due_date': '2025-02-23', 'invoice_id': '66b69fbd-acc1-4b01-b4b7-a33a0e38061f', 'invoice_number': 'INV-2025-0349', 'totalAmount': 2961.76}]
1
25
1000
40

In [48]:
## The key data is the total number of pages in the dataset, so we extract the value in this section:
## We set that value to "pages" and user it later.

pages = data_import['total_pages']
print (pages)

40

In [ ]:
## Visualizing the main data section in the import.

data_import = pd.json_normalize(data_import['data']) 
data_import.head()

,company_id,company_name,counter_party,created_at,currency,invoice_date,invoice_due_date,invoice_id,invoice_number,totalAmount
0,ed811a71-439e-4c49-bfb8-8fb407c39428,DataLake Ventures,Wholesale Dynamics GmbH,2025-01-01 12:00:00,EUR,2025-01-01,2025-02-15,895a6833-d83d-4a5a-a2c3-de35b341d00a,INV-2025-0023,648.15
1,2219af27-6da7-41a3-ac79-abce340fe56d,CloudStream Insights,Global Services Ltd,2025-01-01 08:00:00,EUR,2025-01-01,2025-02-15,4140125e-1f9b-41fb-8af2-df7996ea1e48,INV-2025-0239,2141.18
2,da36911c-7145-4c19-8e82-35c39f3a2e9c,AlgoRhythm Solutions,Cloud Systems,2025-01-01 10:00:00,EUR,2025-01-01,2025-03-02,abed77a5-4581-42f9-adb1-9ca99837e78f,INV-2025-0427,3474.10
3,cc007a93-8d8e-444c-bb8c-ae3db9871347,ByteForge Analytics,Enterprise Solutions AG,2025-01-01 02:00:00,GBP,2025-01-01,2025-03-02,e0e417e9-c2f2-459c-a296-2bc9ca406638,INV-2025-0498,3877.07
4,d66bfb15-e693-4219-9cb0-c5ecbb61a994,ETL Enterprises,Nordic Supply Chain,2025-01-01 05:00:00,EUR,2025-01-01,2025-01-31,095795ca-2eca-499b-805d-82d79bca6cdc,INV-2025-0691,1452.09

## Importing all endpoint data

1) We take the maximum amount of pages that exists in the keys, and loop the endpoint until the maximum page number
2) We import the data and append to a dataframe
3) There are also an extra check embeded, summing all the page_sizes in the loop to verify if its equal to ['total_items']

In [53]:
# Setting initial conditions to run loop
total_entries = 0
page_num = 1
df = pd.DataFrame()

while page_num <= pages:
    endpoint = f'https://europe-west3-recap-dev-347108.cloudfunctions.net/analytics-challenge-api/invoices?page={page_num}'
    response = requests.get(endpoint)
    data_import = response.json()
    df_temp = pd.json_normalize(data_import['data'])
    df = pd.concat([df, df_temp], ignore_index=True)
    total_entries = total_entries + data_import['page_size']
    page_num += 1

### Running Data Checks on DF

Checks to see if data export number of entries matches data

In [54]:
total_entries == data_import['total_items']

True

In [ ]:
## Checking df info after running import
# Take a look into data type outputs and if there are any null values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   company_id        1000 non-null   object
 1   company_name      1000 non-null   object
 2   counter_party     1000 non-null   object
 3   created_at        1000 non-null   object
 4   currency          1000 non-null   object
 5   invoice_date      1000 non-null   object
 6   invoice_due_date  1000 non-null   object
 7   invoice_id        1000 non-null   object
 8   invoice_number    1000 non-null   object
 9   totalAmount       1000 non-null   float64
dtypes: float64(1), object(9)
memory usage: 78.3+ KB

In [56]:
missing_values = df.isnull().sum()
print("Missing Values:")
print(missing_values)

Missing Values:
company_id          0
company_name        0
counter_party       0
created_at          0
currency            0
invoice_date        0
invoice_due_date    0
invoice_id          0
invoice_number      0
totalAmount         0
dtype: int64

### Changing data types of columns

Changing some columns to datetime values

In [57]:
df['created_at'] = pd.to_datetime(df['created_at'])
df['invoice_date'] = pd.to_datetime(df['invoice_date'])
df['invoice_due_date'] = pd.to_datetime(df['invoice_due_date'])

In [ ]:
## Checking info after data type change
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   company_id        1000 non-null   object
 1   company_name      1000 non-null   object
 2   counter_party     1000 non-null   object
 3   created_at        1000 non-null   datetime64[ns]
 4   currency          1000 non-null   object
 5   invoice_date      1000 non-null   datetime64[ns]
 6   invoice_due_date  1000 non-null   datetime64[ns]
 7   invoice_id        1000 non-null   object
 8   invoice_number    1000 non-null   object
 9   totalAmount       1000 non-null   float64
dtypes: datetime64[ns](3), float64(1), object(6)
memory usage: 78.3+ KB

In [58]:
df.head()

,company_id,company_name,counter_party,created_at,currency,invoice_date,invoice_due_date,invoice_id,invoice_number,totalAmount
0,ed811a71-439e-4c49-bfb8-8fb407c39428,DataLake Ventures,Wholesale Dynamics GmbH,2025-01-01 12:00:00,EUR,2025-01-01,2025-02-15,895a6833-d83d-4a5a-a2c3-de35b341d00a,INV-2025-0023,648.15
1,2219af27-6da7-41a3-ac79-abce340fe56d,CloudStream Insights,Global Services Ltd,2025-01-01 08:00:00,EUR,2025-01-01,2025-02-15,4140125e-1f9b-41fb-8af2-df7996ea1e48,INV-2025-0239,2141.18
2,da36911c-7145-4c19-8e82-35c39f3a2e9c,AlgoRhythm Solutions,Cloud Systems,2025-01-01 10:00:00,EUR,2025-01-01,2025-03-02,abed77a5-4581-42f9-adb1-9ca99837e78f,INV-2025-0427,3474.10
3,cc007a93-8d8e-444c-bb8c-ae3db9871347,ByteForge Analytics,Enterprise Solutions AG,2025-01-01 02:00:00,GBP,2025-01-01,2025-03-02,e0e417e9-c2f2-459c-a296-2bc9ca406638,INV-2025-0498,3877.07
4,d66bfb15-e693-4219-9cb0-c5ecbb61a994,ETL Enterprises,Nordic Supply Chain,2025-01-01 05:00:00,EUR,2025-01-01,2025-01-31,095795ca-2eca-499b-805d-82d79bca6cdc,INV-2025-0691,1452.09

## Exporting Data

In [25]:
## Exporting data to a csv file

df.to_csv('endpoint_export.csv', index=False)